import discord

TOKEN ="PUT YOUR TOKEN HERE"

url = "http://127.0.0.1:7860"

pfp = "https://i.postimg.cc/C1YsWR3T/icon.jpg"

colour = discord.Colour.from_str("0x11806a")
red = discord.Colour.from_str("0xFF0000")

negative_prompt = "(deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime:1.4), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck"

original_negative_prompt = negative_prompt

prompt_examples = [
    "RAW photo, 8k UHD, high detailed skin, handsome german hippie, 72yo, bavarian man, green eyes, rule of thirds, masterpiece, photography, ultra realism, realistic, outdoors, golden hour, portrait, smiling, grey short hair, rocker style, DoF, (Hamburg:1.1), harbor, sky, clouds, soft lighting, ( highly detailed skin:0.7),(film grain:1.3), 8k uhd, dslr, soft lighting, high quality, HDRI, Fujifilm XT3 <lora:add_detail:0.66>",
    "photo of top model 18 y.o, cyberpunk art, gothic art, extremely high quality RAW photograph, detailed background, intricate, Exquisite details and textures, highly detailed, ultra detailed photograph, warm lighting, 4k, sharp focus, high resolution, detailed skin, detailed eyes, 8k uhd, dslr, high quality, film grain,",
    "A charming photo of a small bunny. He is wearing a suit. masterpiece, ultra-quality, hyperrealistic, RAW photo, highly detailed, 4k, medium shot, cinematic photography, natural texture, action shot, XF IQ4, 150MP, 50mm, ISO 1000, 1/250s, natural light",
    "A stunning intricate full color portrait of (sks woman:1) as (viking warrior), (barbarian), epic character composition, by ilya kuvshinov, alessio albi, nina masic, sharp focus, natural lighting, subsurface scattering, f2, 35mm, film grain <lora:lora_natalie_v1_from_v1_160:1>",
    "award winning professional photography of (1man:1.5) Athenian man, shaggy layers hairstyle and chinstrap, sad smile, standing with arms crossed in front of body in WWII, Bombed-Out Building Interior, Exposed brickwork, rubble, damaged furniture, evidence of previous life ,(epic scene:1.3), ultra detailed character with perfect face, detailed skin,(ultrasharp:1.3),(masterpiece:1.1),best quality,(photorealistic:1.2), 4k perfect quality, by Ralph Gibson, Split Lighting, dutch angle, focus on face, Magnificent, Imperceptible detail, Intricately designed, (perfect quality face:1.2) hyper-detailed complex, insanely detailed, detailed clothes, detailed skin, detailed body",
    "RAW photo, portrait of a beautiful blonde woman wearing a red shirt (high detailed skin:1.2), 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3",
    "A charming photo of a small anthropomorphic ferret. He is wearing a newsboy cap and has a very long torso masterpiece, ultra-quality, hyperrealistic, RAW photo, highly detailed, 4k, medium shot, cinematic photography, natural texture, action shot, XF IQ4, 150MP, 50mm, ISO 1000, 1/250s, natural light",
    "realistic photo, a realistic photo of 18yo girl in a sundress, blonde hair, beach, (1girl), (extremely detailed CG unity 8k wallpaper), photo of the most beautiful artwork in the world, professional majestic (photography by Steve McCurry), 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3 sharp focus, f 5.6, High Detail, Sharp focus, dramatic, (looking at viewer:1.2), (detailed pupils:1.3), (natural light),",
    "(masterpiece), (extremely intricate:1.3), (realistic), portrait of a girl, the most beautiful in the world, (medieval armor), metal reflections, upper body, outdoors, intense sunlight, far away castle, professional photograph of a stunning woman detailed, sharp focus, dramatic, award winning, cinematic lighting, octane render unreal engine, volumetrics dtx, (film grain, blurry background, blurry foreground, bokeh, depth of field, sunset, motion blur:1.3), chainmail",
    "cgmech, (realistic) solo, white mecha robot, cape, science fiction, torn clothes, glowing, standing, robot joints, mecha, armor, cowboy shot, (floating cape), intense sunlight, silver dragonborn, outdoors, landscape, nature , ((masterpiece, best quality)), <lora:cgmechmix_offset:1><lora:more_details:0.3> <lora:Niji:0.5><lora:dragonborn_offset:0.7> , volumetrics dtx, (film grain, blurry background, blurry foreground, bokeh, depth of field, motion blur:1.3)",
    "masterpiece, (photorealistic:1.4), best quality, beautiful lighting, (ulzzang-6500:0.5), lucy \(cyberpunk\), 1girl, white hair, against railing, arm rest, bangs, bare shoulders, belt, black belt, black leotard, black pants, blurry, bob cut, breasts, building, cityscape, clothing cutout, (cropped jacket), cyberpunk, depth of field, from side, gradient eyes, grey eyes, grey hair, white jacket, leotard, lips, long sleeves, looking afar, looking ahead, (mechanical parts), medium breasts, multicolored eyes, multicolored hair, night, night sky, off shoulder, open clothes, open jacket, outdoors, pants, parted lips, railing, red eyeliner, science fiction, short hair with long locks, short shorts, shorts, sidelocks, sky, solo, standing, teeth, thigh cutout, upper teeth only, white jacket, white shorts, cyberpunk \(series\), cyberpunk edgerunners, RAW photo, 8k uhd, film grain, cosplay, white wig, night, neon lights,,,, <lora:lucy_offset:1.21>",
    "(masterpiece), (extremely intricate), fantasy, (((realistic portrait of an evil hermit, male, villain, anti hero, evil face, masculine face, medium hair, Maroon hair, wicked, cruel, sinister, malicious, ruthless, masculine, athletic))), (((dark bloody clothing, intricate details on clothing))), (perfect composition:1.4), aspect ratio 1:1, beach, deviantart hd, artstation hd, concept art, detailed face and body, award-winning photography, margins, detailed face, professional oil painting by Ed Blinkey, Atey Ghailan, Jeremy Mann, Greg Manchess, Alex Gray, trending on ArtStation, trending on CGSociety, intricate, high detail, sharp focus, dramatic, award winning matte drawing cinematic lighting octane render unreal engine volumetrics dtx",
    "Portrait photo of muscular bearded guy in a worn mech suit, ((light bokeh)), intricate, (steel metal [rust]), elegant, sharp focus, photo by greg rutkowski, soft lighting, vibrant colors, (masterpiece), ((streets)), (detailed face:1.2), (glowing blue eyes:1.1) <lora:FilmVelvia3:0.4> <lora:more_details:0.6>",
    "photo of a supercar, 8k uhd, high quality, road, sunset, motion blur, depth blur, cinematic, filmic image 4k, 8k with [George Miller's Mad Max style]. The image should be [ultra-realistic], with [high-resolution] captured in [natural light]. The lighting should create [soft shadows] and showcase the [raw] and [vibrant colors], volumetric dtx, depth blur, blurry background, bokeh, (motion blur:1.001)",
    "(realistic, photorealistic), dark skinned woman, (Zoe Saldana:0.6), landscape, movie screenshot, sharp details, the expanse scifi spacescape ceres colony, intricate, highly detailed, rich color, smooth, sharp focus, Unreal Engine 5, 8K, (blurry background, film grain, cinema shot, depht blur, volumetric dtx) <lora:star_trek_offset:0.7>",
    "ultra detailed 8k cg, japanese ramen, chopsticks, egg, steam, boken",
    "portrait, action pose, slow motion, (old male human wizard:1.2) old male human wizard wearing yellow and black robes (majestic evoker cloth armor:1.2), (wrinkles, steampunk), (archmage robes, runic patterns:1.2), (insanely detailed, bloom:1.5), (analog:1.2), (high sharpness), (detailed pupils:1.1), (painting:1.1), (digital painting:1), detailed face and eyes, Masterpiece, best quality, (highly detailed photo:1.1), 8k, photorealistic, very long straight white and grey hair, grey streaks, ecstatic, (60-year old Austrian male:1.1), sharp, (older body:1.1), stocky, realistic, real shadow 3d, (highest quality), (concept art, 4k), (wizard labratory in backgound:1.2), by Michelangelo and Alessandro Casagrande and Greg Rutkowski and Sally Mann and jeremy mann and sandra chevrier and maciej kuciara, inspired by (arnold schwarzenegger:1.001) and (Dolph Lundgren:1.001) and (Albert Einstien:1.001)",
    "Vampire Queen, backlit, intricate details, highly detailed, slate atmosphere, cinematic, dimmed colors, dark shot, muted colors, film grain, lut, spooky, depth blur, blurry background dof, bokeh, realistic, realistic skin",
    "RAW photo, face portrait photo of beautiful 26 y.o woman, cute face, wearing black dress, happy face, hard shadows, cinematic shot, dramatic lighting",
    "instagram photo, closeup face photo of 23 y.o Chloe in black sweater, cleavage, pale skin, (smile:0.4), hard shadows",  

]